config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :influencers

  resources :platform_campaigns

  resources :brands

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'admin/dashboard#index'

end

app/models/influencer.rb
# == Schema Information
#
# Table name: influencers
#
#  id                      :integer          not null, primary key
#  first_name              :string(255)
#  last_name               :string(255)
#  email                   :string(255)
#  phone                   :string(255)
#  created_at              :datetime
#  updated_at              :datetime
#  worked_with_mediatrix   :boolean
#  age                     :integer
#  gender                  :boolean
#  ethnicity               :integer
#  kids_age_range_list     :string(255)
#  pet_list                :string(255)
#  alcohol_brand_friendly  :boolean
#  vlogger                 :boolean
#  explicit_content        :boolean
#  brand_safe_content      :boolean
#  brand_exclusives        :text
#  fubr                    :boolean
#  cpa_compensation_basics :text
#  staff_pick              :boolean
#  licensing_included      :boolean
#  primary_language        :integer
#

class Influencer < ActiveRecord::Base

  KIDS_AGE_RANGES = ['No kids', '18+', '14-18', '11-14', '5-111', '2-5', 'Infant']

  GENDERS = {
    'Male' => true,
    'Female' => false
  }

  PETS = ['Dogs', 'Cats', 'Bird', 'Other']

  enum primary_language: {
    english: 1,
    spanish: 2,
    chinese: 3,
    japanese: 4,
    russian: 5,
    portuguese: 6,
    french: 7,
    italian: 8,
    german: 9
  }

  enum ethnicity: {
    white: 1,
    black: 2,
    asian: 3,
    hispanic: 4,
    other: 5
  }

  has_one :address, dependent: :destroy

  has_many :platform_accounts, dependent: :destroy
  has_many :publishing_platforms, through: :platform_accounts

  # Associations to work with admin filters
  has_many :platform_campaigns, through: :publishing_platforms
  has_many :campaigns, through: :platform_campaigns
  has_many :brands, through: :campaigns

  accepts_nested_attributes_for :address

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController
  before_action :set_influencer, only: [:show, :edit, :update, :destroy]

  # GET /influencers
  # GET /influencers.json
  def index
    @influencers = Influencer.all
  end

  # GET /influencers/1
  # GET /influencers/1.json
  def show
  end

  # GET /influencers/new
  def new
    @influencer = Influencer.new
  end

  # GET /influencers/1/edit
  def edit
  end

  # POST /influencers
  # POST /influencers.json
  def create
    @influencer = Influencer.new(influencer_params)

    respond_to do |format|
      if @influencer.save
        format.html { redirect_to @influencer, notice: 'Influencer was successfully created.' }
        format.json { render :show, status: :created, location: @influencer }
      else
        format.html { render :new }
        format.json { render json: @influencer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /influencers/1
  # PATCH/PUT /influencers/1.json
  def update
    respond_to do |format|
      if @influencer.update(influencer_params)
        format.html { redirect_to @influencer, notice: 'Influencer was successfully updated.' }
        format.json { render :show, status: :ok, location: @influencer }
      else
        format.html { render :edit }
        format.json { render json: @influencer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /influencers/1
  # DELETE /influencers/1.json
  def destroy
    @influencer.destroy
    respond_to do |format|
      format.html { redirect_to influencers_url, notice: 'Influencer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_influencer
      @influencer = Influencer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def influencer_params
      params.require(:influencer).permit(:first_name, :last_name, :email, :phone)
    end
end

app/helpers/influencers_helper.rb
module InfluencersHelper
end

app/views/influencers/_form.html.erb
<%= form_for @influencer, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :first_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :last_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :email, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  influencers_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/influencers/edit.html.erb
<%- model_class = Influencer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Influencer %></h1>
</div>
<%= render :partial => 'form' %>

app/views/influencers/index.html.erb
<%- model_class = Influencer -%>
<div class="page-header">
  <h1><%=t '.title', :default => Influencer %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @influencers.each do |influencer| %>
      <tr>
        <td><%= influencer.id %></td>
        <td><%= influencer.first_name %></td>
        <td><%= influencer.last_name %></td>
        <td><%= influencer.email %></td>
        <td><%= influencer.phone %></td>
        <td><%=l influencer.created_at, format: :long %></td>
        <td>
          <%= link_to influencer_path(influencer), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to influencer_path(influencer), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_influencer_path,
            :class => 'btn btn-primary' %>

app/views/influencers/new.html.erb
<%- model_class = Influencer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Influencer %></h1>
</div>
<%= render :partial => 'form' %>

app/views/influencers/show.html.erb
<%- model_class = Influencer -%>
<div class="page-header">
  <h1><%=t '.title', :default => Influencer %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:first_name) %></dt>
      <dd><pre class="prettyprint"><%= @influencer.first_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:last_name) %></dt>
      <dd><pre class="prettyprint"><%= @influencer.last_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email) %></dt>
      <dd><pre class="prettyprint"><%= @influencer.email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone) %></dt>
      <dd><pre class="prettyprint"><%= @influencer.phone %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              influencers_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_influencer_path(@influencer), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              influencer_path(@influencer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>