config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :influencers

  resources :platform_campaigns

  resources :brands

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'admin/dashboard#index'

end

app/models/platform_campaign.rb
# == Schema Information
#
# Table name: platform_campaigns
#
#  id                     :integer          not null, primary key
#  brand_id               :integer
#  created_at             :datetime
#  updated_at             :datetime
#  campaign_id            :integer
#  type                   :string(255)
#  clicks                 :integer
#  comments_count         :integer
#  conversions            :integer
#  facebook_shares        :integer
#  twitter_shares         :integer
#  pins_count             :integer
#  date_live              :datetime
#  num_views              :integer
#  likes                  :integer
#  shares                 :integer
#  num_posts              :integer
#  engagement             :integer
#  snaps                  :integer
#  opens                  :integer
#  retweets               :integer
#  publishing_platform_id :integer
#

class PlatformCampaign < ActiveRecord::Base

  PLATFORMS = %w(
    blog
    facebook
    youtube
    instagram
    snapchat
    twitter
  )

  belongs_to :campaign
  belongs_to :brand
  belongs_to :publishing_platform

  delegate :campaign_name, to: :campaign, allow_nil: true

  before_save :set_brand

  def platform
  end

  def self.stats_fields
    %w(
      clicks
      comments_count
      conversions
      facebook_shares
      twitter_shares
      pins_count
      num_views
      likes
      shares
      num_posts
      engagement
      snaps
      opens
      retweets
    )
  end

  private

  def set_brand
    self.brand_id ||= self.campaign.brand_id
  end
end

app/models/platform_campaigns/blog_platform_campaign.rb
# == Schema Information
#
# Table name: platform_campaigns
#
#  id                     :integer          not null, primary key
#  brand_id               :integer
#  created_at             :datetime
#  updated_at             :datetime
#  campaign_id            :integer
#  type                   :string(255)
#  clicks                 :integer
#  comments_count         :integer
#  conversions            :integer
#  facebook_shares        :integer
#  twitter_shares         :integer
#  pins_count             :integer
#  date_live              :datetime
#  num_views              :integer
#  likes                  :integer
#  shares                 :integer
#  num_posts              :integer
#  engagement             :integer
#  snaps                  :integer
#  opens                  :integer
#  retweets               :integer
#  publishing_platform_id :integer
#

class BlogPlatformCampaign < PlatformCampaign

  def platform
    'blog'
  end

  def self.stats_fields
    %w(
      clicks
      comments_count
      conversions
      facebook_shares
      twitter_shares
      pins_count
    )
  end

end

app/models/platform_campaigns/facebook_platform_campaign.rb
# == Schema Information
#
# Table name: platform_campaigns
#
#  id                     :integer          not null, primary key
#  brand_id               :integer
#  created_at             :datetime
#  updated_at             :datetime
#  campaign_id            :integer
#  type                   :string(255)
#  clicks                 :integer
#  comments_count         :integer
#  conversions            :integer
#  facebook_shares        :integer
#  twitter_shares         :integer
#  pins_count             :integer
#  date_live              :datetime
#  num_views              :integer
#  likes                  :integer
#  shares                 :integer
#  num_posts              :integer
#  engagement             :integer
#  snaps                  :integer
#  opens                  :integer
#  retweets               :integer
#  publishing_platform_id :integer
#

class FacebookPlatformCampaign < PlatformCampaign

  def platform
    'facebook'
  end

  def self.stats_fields
    %w(
      comments_count
      likes
      shares
    )
  end

end

app/models/platform_campaigns/instagram_platform_campaign.rb
# == Schema Information
#
# Table name: platform_campaigns
#
#  id                     :integer          not null, primary key
#  brand_id               :integer
#  created_at             :datetime
#  updated_at             :datetime
#  campaign_id            :integer
#  type                   :string(255)
#  clicks                 :integer
#  comments_count         :integer
#  conversions            :integer
#  facebook_shares        :integer
#  twitter_shares         :integer
#  pins_count             :integer
#  date_live              :datetime
#  num_views              :integer
#  likes                  :integer
#  shares                 :integer
#  num_posts              :integer
#  engagement             :integer
#  snaps                  :integer
#  opens                  :integer
#  retweets               :integer
#  publishing_platform_id :integer
#

class InstagramPlatformCampaign < PlatformCampaign

  def platform
    'instagram'
  end

  def self.stats_fields
    %w(
      comments_count
      likes
      num_posts
      engagement
    )
  end

end

app/models/platform_campaigns/snapchat_platform_campaign.rb
# == Schema Information
#
# Table name: platform_campaigns
#
#  id                     :integer          not null, primary key
#  brand_id               :integer
#  created_at             :datetime
#  updated_at             :datetime
#  campaign_id            :integer
#  type                   :string(255)
#  clicks                 :integer
#  comments_count         :integer
#  conversions            :integer
#  facebook_shares        :integer
#  twitter_shares         :integer
#  pins_count             :integer
#  date_live              :datetime
#  num_views              :integer
#  likes                  :integer
#  shares                 :integer
#  num_posts              :integer
#  engagement             :integer
#  snaps                  :integer
#  opens                  :integer
#  retweets               :integer
#  publishing_platform_id :integer
#

class SnapchatPlatformCampaign < PlatformCampaign

  def platform
    'snapchat'
  end

  def self.stats_fields
    %w(
      snaps
      opens
      conversions
    )
  end

end

app/models/platform_campaigns/twitter_platform_campaign.rb
# == Schema Information
#
# Table name: platform_campaigns
#
#  id                     :integer          not null, primary key
#  brand_id               :integer
#  created_at             :datetime
#  updated_at             :datetime
#  campaign_id            :integer
#  type                   :string(255)
#  clicks                 :integer
#  comments_count         :integer
#  conversions            :integer
#  facebook_shares        :integer
#  twitter_shares         :integer
#  pins_count             :integer
#  date_live              :datetime
#  num_views              :integer
#  likes                  :integer
#  shares                 :integer
#  num_posts              :integer
#  engagement             :integer
#  snaps                  :integer
#  opens                  :integer
#  retweets               :integer
#  publishing_platform_id :integer
#

class TwitterPlatformCampaign < PlatformCampaign

  def platform
    'twitter'
  end

  def self.stats_fields
    %w(
      likes
      retweets
    )
  end

end

app/models/platform_campaigns/youtube_platform_campaign.rb
# == Schema Information
#
# Table name: platform_campaigns
#
#  id                     :integer          not null, primary key
#  brand_id               :integer
#  created_at             :datetime
#  updated_at             :datetime
#  campaign_id            :integer
#  type                   :string(255)
#  clicks                 :integer
#  comments_count         :integer
#  conversions            :integer
#  facebook_shares        :integer
#  twitter_shares         :integer
#  pins_count             :integer
#  date_live              :datetime
#  num_views              :integer
#  likes                  :integer
#  shares                 :integer
#  num_posts              :integer
#  engagement             :integer
#  snaps                  :integer
#  opens                  :integer
#  retweets               :integer
#  publishing_platform_id :integer
#

class YoutubePlatformCampaign < PlatformCampaign

  def platform
    'youtube'
  end

end

app/controllers/platform_campaigns_controller.rb
class PlatformCampaignsController < ApplicationController
  before_action :set_platform_campaign, only: [:show, :edit, :update, :destroy]

  # GET /platform_campaigns
  # GET /platform_campaigns.json
  def index
    @platform_campaigns = PlatformCampaign.all
  end

  # GET /platform_campaigns/1
  # GET /platform_campaigns/1.json
  def show
  end

  # GET /platform_campaigns/new
  def new
    @platform_campaign = PlatformCampaign.new
  end

  # GET /platform_campaigns/1/edit
  def edit
  end

  # POST /platform_campaigns
  # POST /platform_campaigns.json
  def create
    @platform_campaign = PlatformCampaign.new(platform_campaign_params)

    respond_to do |format|
      if @platform_campaign.save
        format.html { redirect_to @platform_campaign, notice: 'Platform campaign was successfully created.' }
        format.json { render :show, status: :created, location: @platform_campaign }
      else
        format.html { render :new }
        format.json { render json: @platform_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platform_campaigns/1
  # PATCH/PUT /platform_campaigns/1.json
  def update
    respond_to do |format|
      if @platform_campaign.update(platform_campaign_params)
        format.html { redirect_to @platform_campaign, notice: 'Platform campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @platform_campaign }
      else
        format.html { render :edit }
        format.json { render json: @platform_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platform_campaigns/1
  # DELETE /platform_campaigns/1.json
  def destroy
    @platform_campaign.destroy
    respond_to do |format|
      format.html { redirect_to platform_campaigns_url, notice: 'Platform campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform_campaign
      @platform_campaign = PlatformCampaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platform_campaign_params
      params.require(:platform_campaign).permit(:name, :contract_num, :brand_id)
    end
end

app/helpers/platform_campaigns_helper.rb
module PlatformCampaignsHelper
end

app/views/platform_campaigns/_form.html.erb
<%= form_for @platform_campaign, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :contract_num, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :contract_num, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  platform_campaigns_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/platform_campaigns/edit.html.erb
<%- model_class = PlatformCampaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => PlatformCampaign %></h1>
</div>
<%= render :partial => 'form' %>

app/views/platform_campaigns/index.html.erb
<%- model_class = PlatformCampaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => PlatformCampaign %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:contract_num) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @platform_campaigns.each do |platform_campaign| %>
      <tr>
        <td><%= platform_campaign.id %></td>
        <td><%= platform_campaign.name %></td>
        <td><%= platform_campaign.contract_num %></td>
        <td><%=l platform_campaign.created_at, format: :long %></td>
        <td>
          <%= link_to platform_campaign_path(platform_campaign), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to platform_campaign_path(platform_campaign), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_platform_campaign_path,
            :class => 'btn btn-primary' %>

app/views/platform_campaigns/new.html.erb
<%- model_class = PlatformCampaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => PlatformCampaign %></h1>
</div>
<%= render :partial => 'form' %>

app/views/platform_campaigns/show.html.erb
<%- model_class = PlatformCampaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => PlatformCampaign %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @platform_campaign.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:contract_num) %></dt>
      <dd><pre class="prettyprint"><%= @platform_campaign.contract_num %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              platform_campaigns_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_platform_campaign_path(@platform_campaign), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              platform_campaign_path(@platform_campaign),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>